### ISSUE TITLE
Update default IP server... again

### ISSUE THREAD

**Issue by 101100** [alessioalex/dynroute#14]
It seems that `http://ip-address.herokuapp.com/ip.json` is no longer available, but there is a new service at `https://api.ipify.org?format=json` with the same result format (info [here](https://www.ipify.org/); it claims to be here for a while).  You may want to update the default.

**Comment by alessioalex** [comment]
@101100 Thanks, will update this. It seems that my free Heroku is being hammered :dagger:

**Comment by alessioalex** [comment]
released a new version with the fix
